version: "3.7"

services:
    app:
        container_name: "${DOCKER_APP}-app"
        build: "${DOCKER_NODE_BUILD}"
        expose:
            - "80"
        labels:
            - traefik.frontend.rule=Host:api.${APP_DOMAIN}
            - traefik.docker.network=${DOCKER_APP}-network
        volumes:
            - "./:/usr/src/app"
        command:
            - "npm"
            - "run"
            - "dev"
        networks:
            backend:
                ipv4_address: "${DOCKER_IPV4_BASE}.10"
    database:
        container_name: "${DOCKER_APP}-database"
        build: "${DOCKER_DB_BUILD}"
        restart: "${DOCKER_RESTART_POLICY}"
        expose:
            - "${DB_PORT}"
        environment:
            # - "MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}"
            # - "MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}"
            - "MONGO_INITDB_DATABASE=${DB_DATABASE}"
        volumes:
            - "${DOCKER_DB_BUILD}/data:/data/db"
        networks:
            backend:
                ipv4_address: "${DOCKER_IPV4_BASE}.15"
    mongo-express:
        container_name: "${DOCKER_APP}-mongo-express"
        image: mongo-express:latest
        expose:
            - "8081"
        labels:
            - traefik.frontend.rule=Host:me.${APP_DOMAIN}
            - traefik.docker.network=${DOCKER_APP}-network
            - traefik.port=8081
        environment:
            - "ME_CONFIG_MONGODB_SERVER=${DB_HOST}"
            - "ME_CONFIG_MONGODB_PORT=${DB_PORT}"
            # - "ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USERNAME}"
            # - "ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASSWORD}"
        networks:
            backend:
                ipv4_address: "${DOCKER_IPV4_BASE}.25"
    traefik:
        image: traefik:1.7
        container_name: "${DOCKER_APP}-traefik"
        restart: "${DOCKER_RESTART_POLICY}"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./traefik.toml:/traefik.toml
            - ./acme.json:/acme.json
        ports:
            - 80:80
            - 8080:8080
        labels:
            - traefik.frontend.rule=Host:proxy.${APP_DOMAIN}
            - traefik.port=8080
        command: --docker
        networks:
            backend:
                ipv4_address: "${DOCKER_IPV4_BASE}.2"

networks:
    backend:
        name: "${DOCKER_APP}-network"
        driver: bridge
        driver_opts:
            com.docker.network.enable_ipv4: "true"
        ipam:
            driver: default
            config:
                - subnet: "${DOCKER_IPV4_BASE}.0/16"
